# TF syntax basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [8]:
print(result)

b'Hello World'


In [9]:
a = tf.constant(10)

In [10]:
b = tf.constant(20)

In [11]:
type(a)

tensorflow.python.framework.ops.Tensor

In [12]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [16]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [17]:
result

30

In [18]:
const = tf.constant(10)

In [19]:
fill_mat = tf.fill((4, 4), 10)

In [21]:
myzeros = tf.zeros((4, 4))

In [22]:
myones = tf.ones((4, 4))

In [23]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [24]:
myrandnu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [25]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandnu]

In [26]:
sess = tf.InteractiveSession()

In [29]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.51111674  0.7799392   0.9660405   1.0291008 ]
 [-1.0692524  -2.3743832   0.05397016  0.50977486]
 [ 1.1838785  -0.37678364 -0.02906079 -0.2952998 ]
 [-0.63905835  1.9671581  -1.1751165   0.10061163]]


[[0.76459014 0.2181617  0.028144   0.18600488]
 [0.76663613 0.90043247 0.07071447 0.38251054]
 [0.40158296 0.2455349  0.76249146 0.09605217]
 [0.7167342  0.96700096 0.20558548 0.69041955]]




In [31]:
a = tf.constant([ [1, 2],
                  [3, 4]])

In [33]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [34]:
b = tf.constant([[1], [100]])

In [35]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [36]:
result = tf.matmul(a, b)

In [37]:
sess.run(result)

array([[201],
       [403]], dtype=int32)

In [38]:
result.eval()

array([[201],
       [403]], dtype=int32)