# Numpy Arrays

In [1]:
my_list = [1, 2, 3, 4, 5]

In [2]:
my_list

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [9]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6]]

In [10]:
mat = np.array(my_mat)

In [11]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0, 11, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((6, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.zeros((4, 4, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
np.random.rand(5)

array([0.99396555, 0.28910323, 0.35750566, 0.60326995, 0.59231562])

In [26]:
np.random.rand(5,5)

array([[0.14505124, 0.52485416, 0.54985894, 0.84456427, 0.34704042],
       [0.59507367, 0.9710269 , 0.72922534, 0.15542144, 0.22633769],
       [0.13002974, 0.60378536, 0.57190261, 0.50151781, 0.06985061],
       [0.62925549, 0.63922966, 0.54739343, 0.34850558, 0.78267902],
       [0.10424879, 0.9320055 , 0.36933875, 0.06380813, 0.52255348]])

In [28]:
np.random.randn(5, 5)

array([[-0.46222316, -0.1898993 ,  1.34827874, -0.55704263, -0.70330583],
       [ 0.16453289, -1.56185426, -0.01711388, -0.24478452, -1.28409175],
       [ 1.54032119, -0.19851433, -0.22924365,  0.52736049, -0.62213732],
       [ 1.15596774, -0.78108818, -0.67769938,  0.52897082, -0.95711613],
       [-1.38641105,  0.04244217,  1.46875044,  0.76434006, -0.61328681]])

In [29]:
np.random.randint(1, 11, 10)

array([4, 2, 5, 2, 4, 7, 1, 8, 8, 6])

In [33]:
arr = np.arange(0, 25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.max()

24

In [39]:
arr = np.random.randint(0, 101, 12)

In [40]:
arr

array([40, 44, 78,  1, 12, 50, 75, 84,  4, 50, 31, 28])

In [42]:
matrix = arr.reshape(4,3)

In [43]:
matrix.argmax()

7

In [44]:
matrix.max()

84

In [46]:
matrix.shape

(4, 3)

In [48]:
matrix.dtype

dtype('int64')