# TensorFlow Estimators

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("iris.csv")

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [5]:
# Colunas nao podem ter spaços

In [6]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [7]:
df.columns = ['sepal_length', 'sepal_width', 'petal_length',
       'petal_width', 'target']

In [8]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'target'], dtype='object')

In [9]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2     0.0
1           4.9          3.0           1.4          0.2     0.0
2           4.7          3.2           1.3          0.2     0.0
3           4.6          3.1           1.5          0.2     0.0
4           5.0          3.6           1.4          0.2     0.0

In [10]:
df["target"] = df["target"].apply(int)

In [11]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  target
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [12]:
y = df["target"]

In [13]:
X = df.drop("target", axis=1)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [16]:
import tensorflow as tf

In [17]:
# feature columns

In [21]:
X.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [20]:
feat_cols = []

for col in X.columns:
    feat_cols.append(tf.feature_column.numeric_column(col))

In [22]:
feat_cols

[_NumericColumn(key='sepal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sepal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_length', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='petal_width', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [23]:
input_func = tf.estimator.inputs.pandas_input_fn(x=X_train, y=y_train, batch_size=10, num_epochs=5, shuffle=True)

In [24]:
input_func

<function tensorflow.python.estimator.inputs.pandas_io.pandas_input_fn.<locals>.input_fn()>

In [25]:
classifier = tf.estimator.DNNClassifier(hidden_units=[10, 20, 10], n_classes=3, feature_columns=feat_cols)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpkjzmq613', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f40c14a4828>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [26]:
classifier.train(input_fn=input_func, steps=50)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpkjzmq613/model.ckpt.
INFO:tensorflow:loss = 15.670624, step = 1
INFO:tensorflow:Saving checkpoints for 50 into /tmp/tmpkjzmq613/model.ckpt.
INFO:tensorflow:Loss for final step: 2.6988034.


In [28]:
pred_fn = tf.estimator.inputs.pandas_input_fn(x=X_test, batch_size=(len(X_test)), shuffle=False)

In [29]:
predictions = list(classifier.predict(input_fn=pred_fn))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpkjzmq613/model.ckpt-50
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [31]:
print(predictions)

[{'logits': array([0.34601477, 1.9023468 , 0.6346447 ], dtype=float32), 'probabilities': array([0.14132285, 0.67006797, 0.18860918], dtype=float32), 'class_ids': array([1]), 'classes': array([b'1'], dtype=object)}, {'logits': array([-2.192235 ,  3.3098445,  3.3595698], dtype=float32), 'probabilities': array([0.00198451, 0.48660365, 0.51141185], dtype=float32), 'class_ids': array([2]), 'classes': array([b'2'], dtype=object)}, {'logits': array([-2.1156747,  3.072796 ,  3.1711144], dtype=float32), 'probabilities': array([0.00264619, 0.4741821 , 0.5231717 ], dtype=float32), 'class_ids': array([2]), 'classes': array([b'2'], dtype=object)}, {'logits': array([-2.2841651,  3.3506227,  3.4908824], dtype=float32), 'probabilities': array([0.00165794, 0.4642215 , 0.53412056], dtype=float32), 'class_ids': array([2]), 'classes': array([b'2'], dtype=object)}, {'logits': array([-1.3885951,  2.6532037,  2.3135164], dtype=float32), 'probabilities': array([0.01015626, 0.57818216, 0.41166157], dtype=float

In [32]:
final_preds = []

for pred in predictions:
    final_preds.append(pred["class_ids"][0])

In [33]:
final_preds

[1,
 2,
 2,
 2,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 2,
 0,
 2,
 1,
 2,
 0,
 2,
 0,
 2,
 0,
 0,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 2]

In [34]:
from sklearn.metrics import classification_report, confusion_matrix

In [35]:
print(confusion_matrix(y_test, final_preds))
print(classification_report(y_test, final_preds))

[[14  0  0]
 [ 0 14  0]
 [ 0  6 16]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       0.70      1.00      0.82        14
          2       1.00      0.73      0.84        22

avg / total       0.92      0.88      0.88        50

